In [1]:
import pandas as pd
import requests

In [5]:
response=requests.get('https://openlibrary.org/search.json?q=harry+potter')

In [7]:
response.json()

{'numFound': 3767,
 'start': 0,
 'numFoundExact': True,
 'num_found': 3767,
 'documentation_url': 'https://openlibrary.org/dev/docs/api/search',
 'q': 'harry potter',
 'offset': None,
 'docs': [{'author_key': ['OL23919A'],
   'author_name': ['J. K. Rowling'],
   'cover_edition_key': 'OL61027601M',
   'cover_i': 15155833,
   'ebook_access': 'borrowable',
   'edition_count': 397,
   'first_publish_year': 1997,
   'has_fulltext': True,
   'ia': ['harrypotterylapi0000rowl_q5r6',
    'harrypottervefel0000rowl',
    'isbn_9788204086600',
    'rbanms.24646.harrypotterphilo000jkro_e4c6',
    'bwb_W9-DHS-647',
    'harrypotter01har0000joan',
    'harrypotterochde0000unse',
    'harijspotersunfi0000unse',
    'halibote0000rowl',
    'harrypotterikami0000unse',
    'isbn_9783551317254',
    'isbn_9788000007885',
    'isbn_6780180353427',
    'isbn_9757501956008',
    'harryzzauberboxb0000jkro',
    'harrypottertome10000jkro',
    'harrypotterylapi0000unse',
    'snj.harrypotterphilo0000jkro_t6f3',
    'snj.harrypotterphilo0001jkro',
    'snj.harrypotterphilo0000jkro_s9g6',
    'harrypotterilape0000jkro',
    'haliboteyumofash0000rowl',
    'harrypotterphilo0000jkro',
    'harrypotterepedr0000jkro',
    'harrypotterogdev0000rowl',
    'harrypotterkamen0000rowl',
    'lccn_078073006991',
    'harrypotterphilo0000jkro_j6k0',
    'harrypottersorce0000unse',
    'harrypotteresbol0000rowl',
    'harrypottersorce0000rowl_a6t2',
    'harrypotterylapi0000rowl',
    'harrypotterylapi0000rowl_d7v1',
    'harrypottermagic0000rowl_p4p3',
    'harrypotteraleco0000rowl',
    'harrypottersorce0000rowl_t5a1',
    'harrypottersorce0000rowl_l6l8',
    'harrypottersorce0000rowl_i9p5',
    'harrypottersorce0000rowl_1998',
    'harrypottersorce0000rowl',
    'harrypotterylapi0000jkro',
    'harrypotterphilo0000rowl_d8d4',
    'harrypotterphilo0000rowl_i7z2',
    'harriuspotteretp0000rowl',
    'harrypotterphilo0000rowl_k0s6',
    'haliboteshenmide0000rowl',
    'hirparaauraprasa0000rowl',
    'haripattervasang0000rowl',
    'areiospoterkaihe00rowl',
    'harrypotterelapi00jkro',
    'harrypottersorce00rowl_1',
    'harrypottersorce00jkro_0',
    'harrypotterikami0000jkro',
    'harrypotterylapi00',
    'haripottatokenja00jkro',
    'harrypottersorce00rowl',
    'harrypottersorc00rowl',
    'harrypottersorce00rowl_0',
    'harrypotterphilo0000rowl_t2o9',
    'harrypotterphilo0000rowl_j1k7',
    'harrypottersorce00jkro',
    'isbn_9789984053851',
    'harrypotterylapi00rowl',
    'harrypotteraguso0000rowl',
    'garripotterifilo00jkro',
    'harrypotterundde0000jkro',
    'harrypotterdhegu0000jkro',
    'harrypotterphilo0000rowl_u9v4',
    'harispoterisiris0000jkro',
    'harripottermaeny0000jkro',
    'harrypotterlcole0000unse',
    'harrypotterochde0000unse_c9n9',
    'harrypotteriharr0000jkro',
    'harrypotterphilo0000rowl',
    'harrypottersorce0000rowl_h8m5',
    'harrypotterundde0000rowl',
    'harriuspotteretp00jkro',
    'harrypotterphilo00rowl_044',
    'harriuspotteretp00rowl',
    'bdrc-W1KG14543'],
   'ia_collection': ['JaiGyan',
    'ServantsOfKnowledge-Print',
    'ambslibrary-ol',
    'americana',
    'americanuniversity-ol',
    'bannedbooks',
    'barryuniversity-ol',
    'belmont-ol',
    'binghamton-ol',
    'bpljordan-ol',
    'brynmawr-ol',
    'buddhist-digital-resource-center',
    'buddhist-digital-resource-center-restricted',
    'cnusd-ol',
    'cua-ol',
    'dartmouthlibrary-ol',
    'delawarecountydistrictlibrary',
    'delawarecountydistrictlibrary-ol',
    'denverpubliclibrary-ol',
    'drakeuniversity-ol',
    'goffstownlibrary-ol',
    'gwulibraries-ol',
    'hamiltonpubliclibrary-ol',
    'inlibrary',
    'internetarchivebooks',
    'ithacacollege-ol',
    'johnshopkins-ol',
    'marymount-ol',
    'miltonpubliclibrary-ol',
    'occidentalcollegelibrary-ol',
    'openlibrary-d-ol',
    'popularchinesebooks',
    'printdisabled',
    'randolph-macon-college-ol',
    'rochester-ol',
    'salisburyfreelibrary-ol',
    'spokanepubliclibrary-ol',
    'the-claremont-colleges-ol',
    'tulsacc-ol',
    'uhmauicollege-ol',
    'unb-ol',
    'uni-ol',
    'universityofarizona-ol',
    'universityofcoloradoboulder-ol',
    'universityofthewest-ol',
    'wilsoncollege-ol',
    'worthingtonlibraries-ol'],
   'key': '/works/OL82563W',
   'language': ['gre',
    'grc',
    'tib',
    'fre',
    'ger',
    'ice',
    'chi',
    'nep',
    'rus',
    'ara',
    'por',
    'lit',
    'lat',
    'pol',
    'bul',
    'cze',
    'yid',
    'heb',
    'jpn',
    'dan',
    'tur',
    'nor',
    'hun',
    'tha',
    'wel',
    'kal',
    'kor',
    'hrv',
    'lav',
    'vie',
    'gle',
    'swe',
    'ukr',
    'alb',
    'eng',
    'hin',
    'ita',
    'rum',
    'mar',
    'ben',
    'gla',
    'urd',
    'afr',
    'per',
    'fin',
    'spa',
    'dut',
    'cat',
    'ltz'],
   'lending_edition_s': 'OL38565767M',
   'lending_identifier_s': 'harrypotterylapi0000rowl_q5r6',
   'public_scan_b': False,
   'series_key': ['OL326110L'],
   'series_name': ['Harry Potter'],
   'series_position': ['1'],
   'title': "Harry Potter and the Philosopher's Stone"},
  {'author_key': ['OL23919A'],
   'author_name': ['J. K. Rowling'],
   'cover_edition_key': 'OL26378158M',
   'cover_i': 15158660,
   'ebook_access': 'printdisabled',
   'edition_count': 144,
   'first_publish_year': 2007,
   'has_fulltext': True,
   'ia': ['harrypotteriinsy0000unse_r7s9',
    'bwb_W8-BSR-221_t9s7',
    'harrypotter7undd0000joan',
    'harrypottereidon0000jkro',
    'garripotteridary0000jkro',
    'haliboteyusiwang0000rowl',
    'haliboteyusiwang0007rowl',
    'isbn_9780606379298',
    'bwb_P9-CCG-593',
    'isbn_9780545010221_z4n9',
    'isbn_9780545010221_i0l2',
    'isbn_9780545010221_r1m3',
    'isbn_9780545010221_x5i4',
    'harrypotter07har0000joan',
    'rbanms.24651.harrypotterdeath0000jkro_e6z9',
    'harrypottereosta0000jkro',
    'harrypotterunddi0000jkro_a5b3',
    'harrypotterdeath0000rowl_n2u6',
    'harrypotterdeath0000rowl_m0z4',
    'harrypotterdeath0000rowl_e0l6',
    'harrypotterdeath0000jkro_w1s3',
    'harrypotterdeath0000rowl_c0f9',
    'harrypotterdeath0000rowl_z5e5',
    'harrypotteretles0000jkro',
    'harrypotteriinsy0000jkro',
    'harrypotterylasr0000unse',
    'isbn_9780545010221',
    'harrypotterylasr00rowl',
    'harrypotteriinsy0000unse',
    'isbn_9781606868829',
    'harrypottereidon0000rowl',
    'haripoteridasikv0000rowl',
    'snj.harrypotterdeath0001unse',
    'harrypotterdeath0000rowl_a4k7',
    'isbn_9780786296651',
    'harrypotterdeath00rowl',
    'harrypotterdeath0000rowl_n2u6',
    'harrypotterdeath2009rowl',
    'garripotteridary0000rowl',
    'harrypotteretles0000rowl'],
   'ia_collection': ['JaiGyan',
    'ServantsOfKnowledge-Print',
    'americana',
    'americanuniversity-ol',
    'bannedbooks',
    'barryuniversity-ol',
    'belmont-ol',
    'bpljordan-ol',
    'cnusd-ol',
    'cua-ol',
    'dartmouthlibrary-ol',
    'delawarecountydistrictlibrary',
    'delawarecountydistrictlibrary-ol',
    'denverpubliclibrary-ol',
    'drakeuniversity-ol',
    'framingham-ol',
    'goffstownlibrary-ol',
    'gwulibraries-ol',
    'internetarchivebooks',
    'ithacacollege-ol',
    'johnshopkins-ol',
    'marygrovecollege',
    'marymount-ol',
    'occidentalcollegelibrary-ol',
    'openlibrary-d-ol',
    'popularchinesebooks',
    'printdisabled',
    'rochester-ol',
    'salisburyfreelibrary-ol',
    'spokanepubliclibrary-ol',
    'the-claremont-colleges-ol',
    'tulsacc-ol',
    'uhmauicollege-ol',
    'unb-ol',
    'uni-ol',
    'universityofarizona-ol',
    'universityofcoloradoboulder-ol',
    'universityofoklahoma-ol',
    'universityofthewest-ol',
    'wilsoncollege-ol',
    'worthingtonlibraries-ol'],
   'key': '/works/OL82586W',
   'language': ['gre',
    'fre',
    'ger',
    'ara',
    'rus',
    'chi',
    'por',
    'pol',
    'bul',
    'heb',
    'cze',
    'jpn',
    'dan',
    'glg',
    'geo',
    'hun',
    'eng',
    'hin',
    'ita',
    'ben',
    'est',
    'spa',
    'cat'],
   'public_scan_b': False,
   'series_key': ['OL326110L'],
   'series_name': ['Harry Potter'],
   'series_position': ['7'],
   'title': 'Harry Potter and the Deathly Hallows'},
  {'author_key': ['OL23919A'],
   'author_name': ['J. K. Rowling'],
   'cover_edition_key': 'OL26234270M',
   'cover_i': 10580435,
   'ebook_access': 'borrowable',
   'edition_count': 279,
   'first_publish_year': 1999,
   'has_fulltext': True,
   'ia': ['bdrc-W8LS66814',
    'rbanms.24648.harrypotterpriso000jkro_w7j2',
    'bwb_S0-ATO-987',
    'isbn_9789994030149',
    'harrypotter03har0000joan',
    'harrypotterielpr0000unse',
    'haliboteyuazikab0000rowl',
    'isbn_9788650509739',
    'isbn_9786041008465_n2s2',
    'harrypotter0000jkro_p4k3',
    'harrypotteryelpr0000unse',
    'harrypotterveazk0000rowl',
    'snj.harrypotterpriso0000rowl_d5x1',
    'harrypotteriwiez0000jkro',
    'harrypotteriwiez0000joan',
    'harrypotterpriso0000unkn',
    'isbn_8934974048480',
    'harrypotterpriso0000rowl_n3b9',
    'harrypotterpriso0000rowl_j5w3',
    'harrypotterpriso00rowl',
    'bwb_W8-BSR-222',
    'harrypotterendeg0000rowl',
    'isbn_9781551926728',
    'isbn_9781551927329',
    'harrypotterpriso0000jkro',
    'harrypottermagic0000rowl_w0z6',
    'harrypotterpriso0000unse_k7c3',
    'haripattervazind0000rowl',
    'harrypotteretlep0000unse',
    'harrypotterpriso0000rowl_v8j4',
    'harrypotteretlep0000rowl_w4j0',
    'harrypotterdheib0000rowl',
    'harrypotterundde0000jkro_v3j2',
    'haliboteazikaban0000rowl',
    'harrypotterendeg0000jkro',
    'harrypotteryelpr0000rowl_p6x6',
    'harrypotteryelpr0000jkro',
    'harrypottersipri0000unse',
    'harrypotteryelpr0000jkro_h0c7',
    'harrypotterpriso0000jkro_l6y6',
    'harrypotterpriso0000rowl_b3s5',
    'harrypotterpriso00jkro_3',
    'harrypotterpriso0000rowl_i0j7',
    'harrypotterpriso0000rowl',
    'harrypotterpriso05rowl',
    'harrypotterpris00rowl',
    'harrypotterprison00rowl',
    'harpotttoazukaba0000rowl',
    'harrypotteretlep0000rowl_t2u0',
    'harrypotteryelpr00jkro',
    'harrypotteryelpr0000rowl_u2s9',
    'harrypotterpriso0000rowl_u4t4',
    'harrypotterpriso00rowl_0',
    'harrypotterandth0000jkro',
    'isbn_9780747546290',
    'harrypotterpriso0000rowl_d0i6',
    'harrypotterpriso0000rowl_v6h7',
    'harrypotterpriso0000rowl_g2m5',
    'harrypotterpriso0000rowl_e2m8',
    'harrypotterpriso0000rowl_z4b1',
    'harrypotteryelpr0000rowl_j2c9',
    'harrypotteryelpr0003rowl',
    'harrypotteryelpr0000rowl',
    'garripotteriuzni0000rowl',
    'harrypotterpriso0000rowl_y6c2',
    'harrypotterpriso0000rowl_a8k5',
    'harrypotterpriso0000rowl_l8l3',
    'harrypotterogfan0000rowl',
    'harrypotterpriso0000rowl_y5h4'],
   'ia_collection': ['California-State-Suggested-Reading',
    'JaiGyan',
    'ServantsOfKnowledge-Print',
    'americana',
    'bannedbooks',
    'books',
    'buddhist-digital-resource-center',
    'buddhist-digital-resource-center-restricted',
    'inlibrary',
    'internetarchivebooks',
    'marygrovecollege',
    'popularchinesebooks',
    'printdisabled'],
   'key': '/works/OL82536W',
   'language': ['gre',
    'tib',
    'fre',
    'ger',
    'chi',
    'ara',
    'rus',
    'por',
    'lit',
    'pol',
    'nob',
    'bul',
    'heb',
    'cze',
    'jpn',
    'tur',
    'arm',
    'geo',
    'hun',
    'tha',
    'kor',
    'vie',
    'swe',
    'alb',
    'hin',
    'eng',
    'ita',
    'rum',
    'mar',
    'ben',
    'urd',
    'srp',
    'per',
    'spa',
    'dut',
    'cat'],
   'lending_edition_s': 'OL48101764M',
   'lending_identifier_s': 'bdrc-W8LS66814',
   'public_scan_b': False,
   'series_key': ['OL326110L'],
   'series_name': ['Harry Potter'],
   'series_position': ['3'],
   'title': 'Harry Potter and the Prisoner of Azkaban'},
  {'author_key': ['OL23919A'],
   'author_name': ['J. K. Rowling'],
   'cover_edition_key': 'OL25683482M',
   'cover_i': 12059372,
   'ebook_access': 'printdisabled',
   'edition_count': 242,
   'first_publish_year': 2000,
   'has_fulltext': True,
   'ia': ['harrypotterogild0000jkro',
    'harrypotterendie0000jkro',
    'harrypotterohniv0000rowl',
    'harrypottericzar0000unse',
    'harrypottersipoc0000jkro',
    'haliboteyuhuoyan0000rowl',
    'bwb_S0-BKQ-107',
    'snj.harrypottergoble0001rowl',
    'harrypottereocal0000jkro',
    'harrypotteryelcl0000unse',
    'bwb_P8-BOL-606',
    'hocharipoterkait0000rowl',
    'rbanms.24649.harrypottergoble0000jkro_w1y9',
    'harrypottergoble0000unse_m7x4',
    'harrypottergoble0000unse_r9q3',
    'harrypottergoble0000jkro_t3n4',
    'harrypottergoble0000unse_l3b9',
    'harrypotterveate0000rowl',
    'harrypottergoble0000jkro',
    'harispoterisirug0000rowl',
    'harrypottergoble0000rowl_m3z2',
    'harrypotteretlac0000rowl_l8z4',
    'harrypottergoble0000unse',
    'harrypottergoble0000rowl_g8u7',
    'harrypottergoble00jkro',
    'harrypottergoble0000rowl_f1q1',
    'harrypotterundde00rowl',
    'harrypotteretlac0000jkro',
    'harrypottergobl00rowl',
    'harrypottergob00rowl',
    'harrypotteryelcl00jkro',
    'harrypotteretlac0000rowl',
    'isbn_9780747574507',
    'garripotterikubo00rowl',
    'harrypottergoble00rowl',
    'harrypottergoble0000rowl_o3u1',
    'harrypotteretlac0000rowl_q9p8',
    'halibotehuobeide00rowl',
    'harrypottericzar0000unse_h2w5',
    'harrypotterendev0000unse',
    'harrypottergoble0000rowl_u7x1',
    'harrypottergoble0000rowl_q6c6',
    'harrypottergoble0000rowl',
    'bwb_C0-BHE-773',
    'harrypotteryelca0000rowl',
    'harrypottergoble0000jkro_e6v5',
    'harrypottergoble0000rowl_x6i6',
    'harrypottergoble0000rowl_k3h6',
    'harrypottergoble0000rowl_b4i1',
    'harrypottergoble0000rowl_f7d0',
    'harrypottergoble0000rowl_y3w0',
    'harrypottergoble0000rowl_r1t8',
    'harrypottergoble0000rowl_q0k2',
    'harrypottergoble0000rowl_z6r7',
    'harrynbsppottery0004jkro',
    'harrypotteryelcl0000jkro',
    'potterharryfireo0000jkro',
    'harrypottereilca0000jkro',
    'harrypotteretlac0000rowl_p7r8',
    'snj.harrypottergoble-2.0001rowl/'],
   'ia_collection': ['California-State-Suggested-Reading',
    'JaiGyan',
    'ServantsOfKnowledge-Print',
    'americana',
    'bannedbooks',
    'books',
    'bpljordan-ol',
    'brynmawr-ol',
    'delawarecountydistrictlibrary',
    'goffstownlibrary-ol',
    'hamiltonpubliclibrary-ol',
    'internetarchivebooks',
    'marygrovecollege',
    'miltonpubliclibrary-ol',
    'openlibrary-d-ol',
    'popularchinesebooks',
    'printdisabled',
    'unb-ol',
    'universityofthewest-ol'],
   'key': '/works/OL82560W',
   'language': ['gre',
    'fre',
    'ger',
    'chi',
    'ara',
    'rus',
    'por',
    'lit',
    'pol',
    'bul',
    'cze',
    'heb',
    'dan',
    'jpn',
    'tur',
    'arm',
    'nor',
    'hun',
    'tha',
    'kor',
    'vie',
    'swe',
    'alb',
    'eng',
    'hin',
    'ita',
    'rum',
    'mar',
    'ben',
    'urd',
    'afr',
    'spa',
    'dut'],
   'public_scan_b': False,
   'series_key': ['OL326110L'],
   'series_name': ['Harry Potter'],
   'series_position': ['4'],
   'title': 'Harry Potter and the Goblet of Fire'},
  {'author_key': ['OL23919A'],
   'author_name': ['J. K. Rowling'],
   'cover_edition_key': 'OL25662116M',
   'cover_i': 15158666,
   'ebook_access': 'printdisabled',
   'edition_count': 247,
   'first_publish_year': 2003,
   'has_fulltext': True,
   'ia': ['isbn_9787020086627_z3i9',
    'harrypotteraniph0000unse',
    'harrypotterochfe0000na',
    'harrypotteriordi0000jkro',
    'harrypotterorder0000rowl_o5k6',
    'harrypotterorder0000rowl_f8o5',
    'haliboteyufenghu0005rowl',
    'haliboteyufenghu0000rowl',
    'isbn_9780329379278',
    'hairparaauramypa0000rowl',
    'harrypotterylaor0000unse_h7v4',
    'rbanms.24748.harrypotterorder0005rowl',
    'harrypotterylaor0000gemm',
    'isbn_9789645757746',
    'harrypotter5undd0000joan',
    'harrypotter05har0000joan',
    'harrypotterorder0000jkro_a2x7',
    'harrypotterorder0000jkro',
    'harrypotterogfni0000unse',
    'harrypotteresfon0000rowl',
    'harispoterisirfe0000rowl',
    'harrypotterorder0000rowl_j7r2',
    'harrypotterylaor0000jkro',
    'harrynbsppottery0000jkro',
    'harrynbsppottery0005jkro',
    'harrypotterorder0000rowl_h2t4',
    'harrypotterorder0000rowl_h7u3',
    'harrypotterorder2004rowl',
    'harrypotterorder0000rowl_g1n2',
    'harrypotterorder0000rowl_o5a3',
    'harripotteriorde0000rowl',
    'harrypotterorder00rowl',
    'harrypotterorder0000rowl_f7t9',
    'harrypotteretlor0000rowl',
    'harrypotterundde0000rowl_z3l1',
    'harptirvamafiliq0000rowl',
    'harrypotterorder00rowl_0',
    'harrypotterorde00rowl_0',
    'snj.harrypotterorder0001rowl_v0o5',
    'snj.harrypotterorder0001rowl',
    'harrypotterorder0000rowl_s1p4',
    'harrypotterorder0000rowl_p8k0',
    'harrypotterylaor0000rowl',
    'harrypottero00rowl',
    'harypotterizakon0000rowl',
    'harrypotterylaor0000rowl_u7k6',
    'harrypotterylaor0000unse',
    'harrypotterorde00jkro',
    'harrypotterorde00rowl',
    'harrypotterorder0000rowl_y4y8'],
   'ia_collection': ['California-State-Suggested-Reading',
    'JaiGyan',
    'ServantsOfKnowledge-Print',
    'americana',
    'bannedbooks',
    'books',
    'delawarecountydistrictlibrary',
    'internetarchivebooks',
    'marygrovecollege',
    'popularchinesebooks',
    'printdisabled',
    'toronto'],
   'key': '/works/OL82548W',
   'language': ['fre',
    'ger',
    'ara',
    'chi',
    'rus',
    'por',
    'lit',
    'pol',
    'bul',
    'heb',
    'cze',
    'dan',
    'jpn',
    'tur',
    'arm',
    'geo',
    'hun',
    'tha',
    'hrv',
    'kor',
    'vie',
    'swe',
    'ukr',
    'eng',
    'hin',
    'ita',
    'rum',
    'ben',
    'per',
    'spa',
    'dut',
    'cat'],
   'public_scan_b': False,
   'series_key': ['OL326110L'],
   'series_name': ['Harry Potter'],
   'series_position': ['5'],
   'title': 'Harry Potter and the Order of the Phoenix'},
  {'author_key': ['OL23919A'],
   'author_name': ['J. K. Rowling'],
   'cover_i': 10716273,
   'ebook_access': 'printdisabled',
   'edition_count': 177,
   'first_publish_year': 2005,
   'has_fulltext': True,
   'ia': ['isbn_9789749907719',
    'rbanms.24650.harrypotterhalfb000jkro_r2k5',
    'harrypottervemel0000jkro',
    'harrypotteryelmi0000rowl',
    'isbn_9788532523105',
    'isbn_9785389077911',
    'haliboteyuhunxue0000rowl',
    'isbn_9788478889945',
    'bwb_S0-DRB-357',
    'isbn_9788183222082',
    'isbn_8934974076780',
    'harrypotteretles0000jkro_c4k4',
    'garripotteriprin0000rowl',
    'harrypotter06har0000joan',
    'harrypotter6undd0000jkro',
    'harrypotterhalfb0000rowl_u7c5',
    'harrypotterhalfb00jkro_2',
    'harrypotterhalfb0006rowl',
    'harrypotterhalfb0000rowl_a0j0',
    'harrypotterhalfb0000jkro_z6k6',
    'harrypotterhalfb0000rowl_v5f6',
    'harrypotterhalfb0000rowl_j1n7',
    'harrypottereopri0000jkro',
    'harrypotteretlep0000jkro',
    'isbn_9788372781680',
    'harrypotterhalfb0000rowl',
    'harrypotterhalfb2005rowl',
    'harrypotterhalf00rowl',
    'isbn_074758110x',
    'harrypotterhalf00rowl_0',
    'halibotehunxuewa0000rowl',
    'harrypotterhalfb0000jkro',
    'harrypotterhalfbrow00rowl',
    'harrypotterundde0000unse',
    'harrypotterhalfb0000rowl_r5b4',
    'harrypotteretlep0000rowl',
    'harrypottereoeni0000rowl',
    'harrypotteretlep0000rowl_q4e4',
    'harrypotterhalfb0000rowl_g4f8',
    'isbn_9780606348539',
    'harrypotterhalfb0000rowl_f5b2'],
   'ia_collection': ['California-State-Suggested-Reading',
    'JaiGyan',
    'ServantsOfKnowledge-Print',
    'americana',
    'bannedbooks',
    'books',
    'brynmawr-ol',
    'cnusd-ol',
    'delawarecountydistrictlibrary',
    'hamiltonpubliclibrary-ol',
    'internetarchivebooks',
    'marygrovecollege',
    'miltonpubliclibrary-ol',
    'openlibrary-d-ol',
    'popularchinesebooks',
    'printdisabled',
    'randolph-macon-college-ol',
    'unb-ol',
    'uni-ol'],
   'key': '/works/OL82565W',

In [43]:
response.json()['docs']

[{'author_key': ['OL23919A'],
  'author_name': ['J. K. Rowling'],
  'cover_edition_key': 'OL61027601M',
  'cover_i': 15155833,
  'ebook_access': 'borrowable',
  'edition_count': 397,
  'first_publish_year': 1997,
  'has_fulltext': True,
  'ia': ['harrypotterylapi0000rowl_q5r6',
   'harrypottervefel0000rowl',
   'isbn_9788204086600',
   'rbanms.24646.harrypotterphilo000jkro_e4c6',
   'bwb_W9-DHS-647',
   'harrypotter01har0000joan',
   'harrypotterochde0000unse',
   'harijspotersunfi0000unse',
   'halibote0000rowl',
   'harrypotterikami0000unse',
   'isbn_9783551317254',
   'isbn_9788000007885',
   'isbn_6780180353427',
   'isbn_9757501956008',
   'harryzzauberboxb0000jkro',
   'harrypottertome10000jkro',
   'harrypotterylapi0000unse',
   'snj.harrypotterphilo0000jkro_t6f3',
   'snj.harrypotterphilo0001jkro',
   'snj.harrypotterphilo0000jkro_s9g6',
   'harrypotterilape0000jkro',
   'haliboteyumofash0000rowl',
   'harrypotterphilo0000jkro',
   'harrypotterepedr0000jkro',
   'harrypotterogdev0000rowl',
   'harrypotterkamen0000rowl',
   'lccn_078073006991',
   'harrypotterphilo0000jkro_j6k0',
   'harrypottersorce0000unse',
   'harrypotteresbol0000rowl',
   'harrypottersorce0000rowl_a6t2',
   'harrypotterylapi0000rowl',
   'harrypotterylapi0000rowl_d7v1',
   'harrypottermagic0000rowl_p4p3',
   'harrypotteraleco0000rowl',
   'harrypottersorce0000rowl_t5a1',
   'harrypottersorce0000rowl_l6l8',
   'harrypottersorce0000rowl_i9p5',
   'harrypottersorce0000rowl_1998',
   'harrypottersorce0000rowl',
   'harrypotterylapi0000jkro',
   'harrypotterphilo0000rowl_d8d4',
   'harrypotterphilo0000rowl_i7z2',
   'harriuspotteretp0000rowl',
   'harrypotterphilo0000rowl_k0s6',
   'haliboteshenmide0000rowl',
   'hirparaauraprasa0000rowl',
   'haripattervasang0000rowl',
   'areiospoterkaihe00rowl',
   'harrypotterelapi00jkro',
   'harrypottersorce00rowl_1',
   'harrypottersorce00jkro_0',
   'harrypotterikami0000jkro',
   'harrypotterylapi00',
   'haripottatokenja00jkro',
   'harrypottersorce00rowl',
   'harrypottersorc00rowl',
   'harrypottersorce00rowl_0',
   'harrypotterphilo0000rowl_t2o9',
   'harrypotterphilo0000rowl_j1k7',
   'harrypottersorce00jkro',
   'isbn_9789984053851',
   'harrypotterylapi00rowl',
   'harrypotteraguso0000rowl',
   'garripotterifilo00jkro',
   'harrypotterundde0000jkro',
   'harrypotterdhegu0000jkro',
   'harrypotterphilo0000rowl_u9v4',
   'harispoterisiris0000jkro',
   'harripottermaeny0000jkro',
   'harrypotterlcole0000unse',
   'harrypotterochde0000unse_c9n9',
   'harrypotteriharr0000jkro',
   'harrypotterphilo0000rowl',
   'harrypottersorce0000rowl_h8m5',
   'harrypotterundde0000rowl',
   'harriuspotteretp00jkro',
   'harrypotterphilo00rowl_044',
   'harriuspotteretp00rowl',
   'bdrc-W1KG14543'],
  'ia_collection': ['JaiGyan',
   'ServantsOfKnowledge-Print',
   'ambslibrary-ol',
   'americana',
   'americanuniversity-ol',
   'bannedbooks',
   'barryuniversity-ol',
   'belmont-ol',
   'binghamton-ol',
   'bpljordan-ol',
   'brynmawr-ol',
   'buddhist-digital-resource-center',
   'buddhist-digital-resource-center-restricted',
   'cnusd-ol',
   'cua-ol',
   'dartmouthlibrary-ol',
   'delawarecountydistrictlibrary',
   'delawarecountydistrictlibrary-ol',
   'denverpubliclibrary-ol',
   'drakeuniversity-ol',
   'goffstownlibrary-ol',
   'gwulibraries-ol',
   'hamiltonpubliclibrary-ol',
   'inlibrary',
   'internetarchivebooks',
   'ithacacollege-ol',
   'johnshopkins-ol',
   'marymount-ol',
   'miltonpubliclibrary-ol',
   'occidentalcollegelibrary-ol',
   'openlibrary-d-ol',
   'popularchinesebooks',
   'printdisabled',
   'randolph-macon-college-ol',
   'rochester-ol',
   'salisburyfreelibrary-ol',
   'spokanepubliclibrary-ol',
   'the-claremont-colleges-ol',
   'tulsacc-ol',
   'uhmauicollege-ol',
   'unb-ol',
   'uni-ol',
   'universityofarizona-ol',
   'universityofcoloradoboulder-ol',
   'universityofthewest-ol',
   'wilsoncollege-ol',
   'worthingtonlibraries-ol'],
  'key': '/works/OL82563W',
  'language': ['gre',
   'grc',
   'tib',
   'fre',
   'ger',
   'ice',
   'chi',
   'nep',
   'rus',
   'ara',
   'por',
   'lit',
   'lat',
   'pol',
   'bul',
   'cze',
   'yid',
   'heb',
   'jpn',
   'dan',
   'tur',
   'nor',
   'hun',
   'tha',
   'wel',
   'kal',
   'kor',
   'hrv',
   'lav',
   'vie',
   'gle',
   'swe',
   'ukr',
   'alb',
   'eng',
   'hin',
   'ita',
   'rum',
   'mar',
   'ben',
   'gla',
   'urd',
   'afr',
   'per',
   'fin',
   'spa',
   'dut',
   'cat',
   'ltz'],
  'lending_edition_s': 'OL38565767M',
  'lending_identifier_s': 'harrypotterylapi0000rowl_q5r6',
  'public_scan_b': False,
  'series_key': ['OL326110L'],
  'series_name': ['Harry Potter'],
  'series_position': ['1'],
  'title': "Harry Potter and the Philosopher's Stone"},
 {'author_key': ['OL23919A'],
  'author_name': ['J. K. Rowling'],
  'cover_edition_key': 'OL26378158M',
  'cover_i': 15158660,
  'ebook_access': 'printdisabled',
  'edition_count': 144,
  'first_publish_year': 2007,
  'has_fulltext': True,
  'ia': ['harrypotteriinsy0000unse_r7s9',
   'bwb_W8-BSR-221_t9s7',
   'harrypotter7undd0000joan',
   'harrypottereidon0000jkro',
   'garripotteridary0000jkro',
   'haliboteyusiwang0000rowl',
   'haliboteyusiwang0007rowl',
   'isbn_9780606379298',
   'bwb_P9-CCG-593',
   'isbn_9780545010221_z4n9',
   'isbn_9780545010221_i0l2',
   'isbn_9780545010221_r1m3',
   'isbn_9780545010221_x5i4',
   'harrypotter07har0000joan',
   'rbanms.24651.harrypotterdeath0000jkro_e6z9',
   'harrypottereosta0000jkro',
   'harrypotterunddi0000jkro_a5b3',
   'harrypotterdeath0000rowl_n2u6',
   'harrypotterdeath0000rowl_m0z4',
   'harrypotterdeath0000rowl_e0l6',
   'harrypotterdeath0000jkro_w1s3',
   'harrypotterdeath0000rowl_c0f9',
   'harrypotterdeath0000rowl_z5e5',
   'harrypotteretles0000jkro',
   'harrypotteriinsy0000jkro',
   'harrypotterylasr0000unse',
   'isbn_9780545010221',
   'harrypotterylasr00rowl',
   'harrypotteriinsy0000unse',
   'isbn_9781606868829',
   'harrypottereidon0000rowl',
   'haripoteridasikv0000rowl',
   'snj.harrypotterdeath0001unse',
   'harrypotterdeath0000rowl_a4k7',
   'isbn_9780786296651',
   'harrypotterdeath00rowl',
   'harrypotterdeath0000rowl_n2u6',
   'harrypotterdeath2009rowl',
   'garripotteridary0000rowl',
   'harrypotteretles0000rowl'],
  'ia_collection': ['JaiGyan',
   'ServantsOfKnowledge-Print',
   'americana',
   'americanuniversity-ol',
   'bannedbooks',
   'barryuniversity-ol',
   'belmont-ol',
   'bpljordan-ol',
   'cnusd-ol',
   'cua-ol',
   'dartmouthlibrary-ol',
   'delawarecountydistrictlibrary',
   'delawarecountydistrictlibrary-ol',
   'denverpubliclibrary-ol',
   'drakeuniversity-ol',
   'framingham-ol',
   'goffstownlibrary-ol',
   'gwulibraries-ol',
   'internetarchivebooks',
   'ithacacollege-ol',
   'johnshopkins-ol',
   'marygrovecollege',
   'marymount-ol',
   'occidentalcollegelibrary-ol',
   'openlibrary-d-ol',
   'popularchinesebooks',
   'printdisabled',
   'rochester-ol',
   'salisburyfreelibrary-ol',
   'spokanepubliclibrary-ol',
   'the-claremont-colleges-ol',
   'tulsacc-ol',
   'uhmauicollege-ol',
   'unb-ol',
   'uni-ol',
   'universityofarizona-ol',
   'universityofcoloradoboulder-ol',
   'universityofoklahoma-ol',
   'universityofthewest-ol',
   'wilsoncollege-ol',
   'worthingtonlibraries-ol'],
  'key': '/works/OL82586W',
  'language': ['gre',
   'fre',
   'ger',
   'ara',
   'rus',
   'chi',
   'por',
   'pol',
   'bul',
   'heb',
   'cze',
   'jpn',
   'dan',
   'glg',
   'geo',
   'hun',
   'eng',
   'hin',
   'ita',
   'ben',
   'est',
   'spa',
   'cat'],
  'public_scan_b': False,
  'series_key': ['OL326110L'],
  'series_name': ['Harry Potter'],
  'series_position': ['7'],
  'title': 'Harry Potter and the Deathly Hallows'},
 {'author_key': ['OL23919A'],
  'author_name': ['J. K. Rowling'],
  'cover_edition_key': 'OL26234270M',
  'cover_i': 10580435,
  'ebook_access': 'borrowable',
  'edition_count': 279,
  'first_publish_year': 1999,
  'has_fulltext': True,
  'ia': ['bdrc-W8LS66814',
   'rbanms.24648.harrypotterpriso000jkro_w7j2',
   'bwb_S0-ATO-987',
   'isbn_9789994030149',
   'harrypotter03har0000joan',
   'harrypotterielpr0000unse',
   'haliboteyuazikab0000rowl',
   'isbn_9788650509739',
   'isbn_9786041008465_n2s2',
   'harrypotter0000jkro_p4k3',
   'harrypotteryelpr0000unse',
   'harrypotterveazk0000rowl',
   'snj.harrypotterpriso0000rowl_d5x1',
   'harrypotteriwiez0000jkro',
   'harrypotteriwiez0000joan',
   'harrypotterpriso0000unkn',
   'isbn_8934974048480',
   'harrypotterpriso0000rowl_n3b9',
   'harrypotterpriso0000rowl_j5w3',
   'harrypotterpriso00rowl',
   'bwb_W8-BSR-222',
   'harrypotterendeg0000rowl',
   'isbn_9781551926728',
   'isbn_9781551927329',
   'harrypotterpriso0000jkro',
   'harrypottermagic0000rowl_w0z6',
   'harrypotterpriso0000unse_k7c3',
   'haripattervazind0000rowl',
   'harrypotteretlep0000unse',
   'harrypotterpriso0000rowl_v8j4',
   'harrypotteretlep0000rowl_w4j0',
   'harrypotterdheib0000rowl',
   'harrypotterundde0000jkro_v3j2',
   'haliboteazikaban0000rowl',
   'harrypotterendeg0000jkro',
   'harrypotteryelpr0000rowl_p6x6',
   'harrypotteryelpr0000jkro',
   'harrypottersipri0000unse',
   'harrypotteryelpr0000jkro_h0c7',
   'harrypotterpriso0000jkro_l6y6',
   'harrypotterpriso0000rowl_b3s5',
   'harrypotterpriso00jkro_3',
   'harrypotterpriso0000rowl_i0j7',
   'harrypotterpriso0000rowl',
   'harrypotterpriso05rowl',
   'harrypotterpris00rowl',
   'harrypotterprison00rowl',
   'harpotttoazukaba0000rowl',
   'harrypotteretlep0000rowl_t2u0',
   'harrypotteryelpr00jkro',
   'harrypotteryelpr0000rowl_u2s9',
   'harrypotterpriso0000rowl_u4t4',
   'harrypotterpriso00rowl_0',
   'harrypotterandth0000jkro',
   'isbn_9780747546290',
   'harrypotterpriso0000rowl_d0i6',
   'harrypotterpriso0000rowl_v6h7',
   'harrypotterpriso0000rowl_g2m5',
   'harrypotterpriso0000rowl_e2m8',
   'harrypotterpriso0000rowl_z4b1',
   'harrypotteryelpr0000rowl_j2c9',
   'harrypotteryelpr0003rowl',
   'harrypotteryelpr0000rowl',
   'garripotteriuzni0000rowl',
   'harrypotterpriso0000rowl_y6c2',
   'harrypotterpriso0000rowl_a8k5',
   'harrypotterpriso0000rowl_l8l3',
   'harrypotterogfan0000rowl',
   'harrypotterpriso0000rowl_y5h4'],
  'ia_collection': ['California-State-Suggested-Reading',
   'JaiGyan',
   'ServantsOfKnowledge-Print',
   'americana',
   'bannedbooks',
   'books',
   'buddhist-digital-resource-center',
   'buddhist-digital-resource-center-restricted',
   'inlibrary',
   'internetarchivebooks',
   'marygrovecollege',
   'popularchinesebooks',
   'printdisabled'],
  'key': '/works/OL82536W',
  'language': ['gre',
   'tib',
   'fre',
   'ger',
   'chi',
   'ara',
   'rus',
   'por',
   'lit',
   'pol',
   'nob',
   'bul',
   'heb',
   'cze',
   'jpn',
   'tur',
   'arm',
   'geo',
   'hun',
   'tha',
   'kor',
   'vie',
   'swe',
   'alb',
   'hin',
   'eng',
   'ita',
   'rum',
   'mar',
   'ben',
   'urd',
   'srp',
   'per',
   'spa',
   'dut',
   'cat'],
  'lending_edition_s': 'OL48101764M',
  'lending_identifier_s': 'bdrc-W8LS66814',
  'public_scan_b': False,
  'series_key': ['OL326110L'],
  'series_name': ['Harry Potter'],
  'series_position': ['3'],
  'title': 'Harry Potter and the Prisoner of Azkaban'},
 {'author_key': ['OL23919A'],
  'author_name': ['J. K. Rowling'],
  'cover_edition_key': 'OL25683482M',
  'cover_i': 12059372,
  'ebook_access': 'printdisabled',
  'edition_count': 242,
  'first_publish_year': 2000,
  'has_fulltext': True,
  'ia': ['harrypotterogild0000jkro',
   'harrypotterendie0000jkro',
   'harrypotterohniv0000rowl',
   'harrypottericzar0000unse',
   'harrypottersipoc0000jkro',
   'haliboteyuhuoyan0000rowl',
   'bwb_S0-BKQ-107',
   'snj.harrypottergoble0001rowl',
   'harrypottereocal0000jkro',
   'harrypotteryelcl0000unse',
   'bwb_P8-BOL-606',
   'hocharipoterkait0000rowl',
   'rbanms.24649.harrypottergoble0000jkro_w1y9',
   'harrypottergoble0000unse_m7x4',
   'harrypottergoble0000unse_r9q3',
   'harrypottergoble0000jkro_t3n4',
   'harrypottergoble0000unse_l3b9',
   'harrypotterveate0000rowl',
   'harrypottergoble0000jkro',
   'harispoterisirug0000rowl',
   'harrypottergoble0000rowl_m3z2',
   'harrypotteretlac0000rowl_l8z4',
   'harrypottergoble0000unse',
   'harrypottergoble0000rowl_g8u7',
   'harrypottergoble00jkro',
   'harrypottergoble0000rowl_f1q1',
   'harrypotterundde00rowl',
   'harrypotteretlac0000jkro',
   'harrypottergobl00rowl',
   'harrypottergob00rowl',
   'harrypotteryelcl00jkro',
   'harrypotteretlac0000rowl',
   'isbn_9780747574507',
   'garripotterikubo00rowl',
   'harrypottergoble00rowl',
   'harrypottergoble0000rowl_o3u1',
   'harrypotteretlac0000rowl_q9p8',
   'halibotehuobeide00rowl',
   'harrypottericzar0000unse_h2w5',
   'harrypotterendev0000unse',
   'harrypottergoble0000rowl_u7x1',
   'harrypottergoble0000rowl_q6c6',
   'harrypottergoble0000rowl',
   'bwb_C0-BHE-773',
   'harrypotteryelca0000rowl',
   'harrypottergoble0000jkro_e6v5',
   'harrypottergoble0000rowl_x6i6',
   'harrypottergoble0000rowl_k3h6',
   'harrypottergoble0000rowl_b4i1',
   'harrypottergoble0000rowl_f7d0',
   'harrypottergoble0000rowl_y3w0',
   'harrypottergoble0000rowl_r1t8',
   'harrypottergoble0000rowl_q0k2',
   'harrypottergoble0000rowl_z6r7',
   'harrynbsppottery0004jkro',
   'harrypotteryelcl0000jkro',
   'potterharryfireo0000jkro',
   'harrypottereilca0000jkro',
   'harrypotteretlac0000rowl_p7r8',
   'snj.harrypottergoble-2.0001rowl/'],
  'ia_collection': ['California-State-Suggested-Reading',
   'JaiGyan',
   'ServantsOfKnowledge-Print',
   'americana',
   'bannedbooks',
   'books',
   'bpljordan-ol',
   'brynmawr-ol',
   'delawarecountydistrictlibrary',
   'goffstownlibrary-ol',
   'hamiltonpubliclibrary-ol',
   'internetarchivebooks',
   'marygrovecollege',
   'miltonpubliclibrary-ol',
   'openlibrary-d-ol',
   'popularchinesebooks',
   'printdisabled',
   'unb-ol',
   'universityofthewest-ol'],
  'key': '/works/OL82560W',
  'language': ['gre',
   'fre',
   'ger',
   'chi',
   'ara',
   'rus',
   'por',
   'lit',
   'pol',
   'bul',
   'cze',
   'heb',
   'dan',
   'jpn',
   'tur',
   'arm',
   'nor',
   'hun',
   'tha',
   'kor',
   'vie',
   'swe',
   'alb',
   'eng',
   'hin',
   'ita',
   'rum',
   'mar',
   'ben',
   'urd',
   'afr',
   'spa',
   'dut'],
  'public_scan_b': False,
  'series_key': ['OL326110L'],
  'series_name': ['Harry Potter'],
  'series_position': ['4'],
  'title': 'Harry Potter and the Goblet of Fire'},
 {'author_key': ['OL23919A'],
  'author_name': ['J. K. Rowling'],
  'cover_edition_key': 'OL25662116M',
  'cover_i': 15158666,
  'ebook_access': 'printdisabled',
  'edition_count': 247,
  'first_publish_year': 2003,
  'has_fulltext': True,
  'ia': ['isbn_9787020086627_z3i9',
   'harrypotteraniph0000unse',
   'harrypotterochfe0000na',
   'harrypotteriordi0000jkro',
   'harrypotterorder0000rowl_o5k6',
   'harrypotterorder0000rowl_f8o5',
   'haliboteyufenghu0005rowl',
   'haliboteyufenghu0000rowl',
   'isbn_9780329379278',
   'hairparaauramypa0000rowl',
   'harrypotterylaor0000unse_h7v4',
   'rbanms.24748.harrypotterorder0005rowl',
   'harrypotterylaor0000gemm',
   'isbn_9789645757746',
   'harrypotter5undd0000joan',
   'harrypotter05har0000joan',
   'harrypotterorder0000jkro_a2x7',
   'harrypotterorder0000jkro',
   'harrypotterogfni0000unse',
   'harrypotteresfon0000rowl',
   'harispoterisirfe0000rowl',
   'harrypotterorder0000rowl_j7r2',
   'harrypotterylaor0000jkro',
   'harrynbsppottery0000jkro',
   'harrynbsppottery0005jkro',
   'harrypotterorder0000rowl_h2t4',
   'harrypotterorder0000rowl_h7u3',
   'harrypotterorder2004rowl',
   'harrypotterorder0000rowl_g1n2',
   'harrypotterorder0000rowl_o5a3',
   'harripotteriorde0000rowl',
   'harrypotterorder00rowl',
   'harrypotterorder0000rowl_f7t9',
   'harrypotteretlor0000rowl',
   'harrypotterundde0000rowl_z3l1',
   'harptirvamafiliq0000rowl',
   'harrypotterorder00rowl_0',
   'harrypotterorde00rowl_0',
   'snj.harrypotterorder0001rowl_v0o5',
   'snj.harrypotterorder0001rowl',
   'harrypotterorder0000rowl_s1p4',
   'harrypotterorder0000rowl_p8k0',
   'harrypotterylaor0000rowl',
   'harrypottero00rowl',
   'harypotterizakon0000rowl',
   'harrypotterylaor0000rowl_u7k6',
   'harrypotterylaor0000unse',
   'harrypotterorde00jkro',
   'harrypotterorde00rowl',
   'harrypotterorder0000rowl_y4y8'],
  'ia_collection': ['California-State-Suggested-Reading',
   'JaiGyan',
   'ServantsOfKnowledge-Print',
   'americana',
   'bannedbooks',
   'books',
   'delawarecountydistrictlibrary',
   'internetarchivebooks',
   'marygrovecollege',
   'popularchinesebooks',
   'printdisabled',
   'toronto'],
  'key': '/works/OL82548W',
  'language': ['fre',
   'ger',
   'ara',
   'chi',
   'rus',
   'por',
   'lit',
   'pol',
   'bul',
   'heb',
   'cze',
   'dan',
   'jpn',
   'tur',
   'arm',
   'geo',
   'hun',
   'tha',
   'hrv',
   'kor',
   'vie',
   'swe',
   'ukr',
   'eng',
   'hin',
   'ita',
   'rum',
   'ben',
   'per',
   'spa',
   'dut',
   'cat'],
  'public_scan_b': False,
  'series_key': ['OL326110L'],
  'series_name': ['Harry Potter'],
  'series_position': ['5'],
  'title': 'Harry Potter and the Order of the Phoenix'},
 {'author_key': ['OL23919A'],
  'author_name': ['J. K. Rowling'],
  'cover_i': 10716273,
  'ebook_access': 'printdisabled',
  'edition_count': 177,
  'first_publish_year': 2005,
  'has_fulltext': True,
  'ia': ['isbn_9789749907719',
   'rbanms.24650.harrypotterhalfb000jkro_r2k5',
   'harrypottervemel0000jkro',
   'harrypotteryelmi0000rowl',
   'isbn_9788532523105',
   'isbn_9785389077911',
   'haliboteyuhunxue0000rowl',
   'isbn_9788478889945',
   'bwb_S0-DRB-357',
   'isbn_9788183222082',
   'isbn_8934974076780',
   'harrypotteretles0000jkro_c4k4',
   'garripotteriprin0000rowl',
   'harrypotter06har0000joan',
   'harrypotter6undd0000jkro',
   'harrypotterhalfb0000rowl_u7c5',
   'harrypotterhalfb00jkro_2',
   'harrypotterhalfb0006rowl',
   'harrypotterhalfb0000rowl_a0j0',
   'harrypotterhalfb0000jkro_z6k6',
   'harrypotterhalfb0000rowl_v5f6',
   'harrypotterhalfb0000rowl_j1n7',
   'harrypottereopri0000jkro',
   'harrypotteretlep0000jkro',
   'isbn_9788372781680',
   'harrypotterhalfb0000rowl',
   'harrypotterhalfb2005rowl',
   'harrypotterhalf00rowl',
   'isbn_074758110x',
   'harrypotterhalf00rowl_0',
   'halibotehunxuewa0000rowl',
   'harrypotterhalfb0000jkro',
   'harrypotterhalfbrow00rowl',
   'harrypotterundde0000unse',
   'harrypotterhalfb0000rowl_r5b4',
   'harrypotteretlep0000rowl',
   'harrypottereoeni0000rowl',
   'harrypotteretlep0000rowl_q4e4',
   'harrypotterhalfb0000rowl_g4f8',
   'isbn_9780606348539',
   'harrypotterhalfb0000rowl_f5b2'],
  'ia_collection': ['California-State-Suggested-Reading',
   'JaiGyan',
   'ServantsOfKnowledge-Print',
   'americana',
   'bannedbooks',
   'books',
   'brynmawr-ol',
   'cnusd-ol',
   'delawarecountydistrictlibrary',
   'hamiltonpubliclibrary-ol',
   'internetarchivebooks',
   'marygrovecollege',
   'miltonpubliclibrary-ol',
   'openlibrary-d-ol',
   'popularchinesebooks',
   'printdisabled',
   'randolph-macon-college-ol',
   'unb-ol',
   'uni-ol'],
  'key': '/works/OL82565W',
  'language': ['gre',
   'fre',
   'ger',
   'ara',
   'rus',
   'chi',
   'por',
   'pol',
   'bul',
   'heb',
   'jpn',
   'tur',
   'hun',
   'tha',
   'hrv',
   'vie',
   'hin',
   'eng',
   'ita',
   'ben',
   'per',
   'spa'],
  'public_scan_b': False,
  'series_key': ['OL326110L'],
  'series_name': ['Harry Potter'],
  'series_position': ['6'],
  'title': 'Harry Potter and the Half-Blood Prince'},
 {'author_key': ['OL23919A'],
  'author_name': ['J. K. Rowling'],
  'cover_edition_key': 'OL59041259M',
  'cover_i': 15158664,
  'ebook_access': 'printdisabled',
  'edition_count': 305,
  'first_publish_year': 1998,
  'has_fulltext': True,
  'ia': ['snj.harrypotter0000jkro_e1f9',
   'harptirvaufrahia0000rowl',
   'harrypotterochhe0000unse',
   'harrypotterilaca0000rowl',
   'harrypotterchamb0000na',
   'harrypotteroghem0000jkro',
   'rbanms.24647.harrypotterchamb0000jkro_v5z1',
   'harrypotterchamb0000jkro_w5l2',

In [21]:
pd.DataFrame(response.json()['docs']).head(5)

,author_key,author_name,cover_edition_key,cover_i,ebook_access,edition_count,first_publish_year,has_fulltext,ia,ia_collection,key,language,lending_edition_s,lending_identifier_s,public_scan_b,series_key,series_name,series_position,title,subtitle
0,[OL23919A],[J. K. Rowling],OL61027601M,15155833.0,borrowable,397,1997.0,True,"[harrypotterylapi0000rowl_q5r6, harrypottervef...","[JaiGyan, ServantsOfKnowledge-Print, ambslibra...",/works/OL82563W,"[gre, grc, tib, fre, ger, ice, chi, nep, rus, ...",OL38565767M,harrypotterylapi0000rowl_q5r6,False,[OL326110L],[Harry Potter],[1],Harry Potter and the Philosopher's Stone,NaN
1,[OL23919A],[J. K. Rowling],OL26378158M,15158660.0,printdisabled,144,2007.0,True,"[harrypotteriinsy0000unse_r7s9, bwb_W8-BSR-221...","[JaiGyan, ServantsOfKnowledge-Print, americana...",/works/OL82586W,"[gre, fre, ger, ara, rus, chi, por, pol, bul, ...",NaN,NaN,False,[OL326110L],[Harry Potter],[7],Harry Potter and the Deathly Hallows,NaN
2,[OL23919A],[J. K. Rowling],OL26234270M,10580435.0,borrowable,279,1999.0,True,"[bdrc-W8LS66814, rbanms.24648.harrypotterpriso...","[California-State-Suggested-Reading, JaiGyan, ...",/works/OL82536W,"[gre, tib, fre, ger, chi, ara, rus, por, lit, ...",OL48101764M,bdrc-W8LS66814,False,[OL326110L],[Harry Potter],[3],Harry Potter and the Prisoner of Azkaban,NaN
3,[OL23919A],[J. K. Rowling],OL25683482M,12059372.0,printdisabled,242,2000.0,True,"[harrypotterogild0000jkro, harrypotterendie000...","[California-State-Suggested-Reading, JaiGyan, ...",/works/OL82560W,"[gre, fre, ger, chi, ara, rus, por, lit, pol, ...",NaN,NaN,False,[OL326110L],[Harry Potter],[4],Harry Potter and the Goblet of Fire,NaN
4,[OL23919A],[J. K. Rowling],OL25662116M,15158666.0,printdisabled,247,2003.0,True,"[isbn_9787020086627_z3i9, harrypotteraniph0000...","[California-State-Suggested-Reading, JaiGyan, ...",/works/OL82548W,"[fre, ger, ara, chi, rus, por, lit, pol, bul, ...",NaN,NaN,False,[OL326110L],[Harry Potter],[5],Harry Potter and the Order of the Phoenix,NaN

In [31]:
df=pd.DataFrame(response.json()['docs'])[['author_name', 'title','language']]

In [37]:
df.head()

,author_name,title,language
0,[J. K. Rowling],Harry Potter and the Philosopher's Stone,"[gre, grc, tib, fre, ger, ice, chi, nep, rus, ..."
1,[J. K. Rowling],Harry Potter and the Deathly Hallows,"[gre, fre, ger, ara, rus, chi, por, pol, bul, ..."
2,[J. K. Rowling],Harry Potter and the Prisoner of Azkaban,"[gre, tib, fre, ger, chi, ara, rus, por, lit, ..."
3,[J. K. Rowling],Harry Potter and the Goblet of Fire,"[gre, fre, ger, chi, ara, rus, por, lit, pol, ..."
4,[J. K. Rowling],Harry Potter and the Order of the Phoenix,"[fre, ger, ara, chi, rus, por, lit, pol, bul, ..."

In [39]:
df=pd.DataFrame()

In [41]:
df

Empty DataFrame
Columns: []
Index: []

In [57]:
pd.DataFrame(all_data).columns.tolist()

['author_key',
 'author_name',
 'cover_edition_key',
 'cover_i',
 'ebook_access',
 'edition_count',
 'first_publish_year',
 'has_fulltext',
 'ia',
 'ia_collection',
 'key',
 'language',
 'lending_edition_s',
 'lending_identifier_s',
 'public_scan_b',
 'series_key',
 'series_name',
 'series_position',
 'title',
 'subtitle']

In [61]:
df = pd.DataFrame(all_data)[['title', 'subtitle', 'author_name', 
                               'language', 'first_publish_year', 
                               'edition_count', 'ebook_access',
                               'series_name', 'has_fulltext']]

In [63]:
df

,title,subtitle,author_name,language,first_publish_year,edition_count,ebook_access,series_name,has_fulltext
0,Harry Potter and the Philosopher's Stone,NaN,[J. K. Rowling],"[gre, grc, tib, fre, ger, ice, chi, nep, rus, ...",1997.0,397,borrowable,[Harry Potter],True
1,Harry Potter and the Deathly Hallows,NaN,[J. K. Rowling],"[gre, fre, ger, ara, rus, chi, por, pol, bul, ...",2007.0,144,printdisabled,[Harry Potter],True
2,Harry Potter and the Prisoner of Azkaban,NaN,[J. K. Rowling],"[gre, tib, fre, ger, chi, ara, rus, por, lit, ...",1999.0,279,borrowable,[Harry Potter],True
3,Harry Potter and the Goblet of Fire,NaN,[J. K. Rowling],"[gre, fre, ger, chi, ara, rus, por, lit, pol, ...",2000.0,242,printdisabled,[Harry Potter],True
4,Harry Potter and the Order of the Phoenix,NaN,[J. K. Rowling],"[fre, ger, ara, chi, rus, por, lit, pol, bul, ...",2003.0,247,printdisabled,[Harry Potter],True
...,...,...,...,...,...,...,...,...,...
9895,Harry Potter Cocktails,NaN,[Edric L. Granger],[eng],2020.0,1,no_ebook,NaN,False
9896,Harry Potter Quizzes : Metal Perk,NaN,[Jake HOWARD],[eng],2020.0,1,no_ebook,NaN,False
9897,Emma Watson : Harry Potter Star,NaN,[Sarah Tieck],[eng],2010.0,1,no_ebook,NaN,False
9898,Daniel Radcliffe : Harry Potter Star,NaN,[Sarah Tieck],[eng],2010.0,1,no_ebook,NaN,False
9899,Harry Potter Colouring Book,NaN,[Garry Potter],[eng],2016.0,1,no_ebook,NaN,False

In [65]:
df.to_csv('harry_potter_books.csv', index=False)